### home
GET http://localhost:3000/home
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoic2VjcmV0IiwiaWF0IjoxNzEwODc4Mzk2fQ.gFrL3GEGxwiQ3FHs0mjdMv3Ua0FYjHeJwxrBs-ZJRus


### top-ten crytpocurencies
GET http://localhost:3000/top-ten 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoic2VjcmV0IiwiaWF0IjoxNzEwODc4Mzk2fQ.gFrL3GEGxwiQ3FHs0mjdMv3Ua0FYjHeJwxrBs-ZJRus


###
POST http://localhost:3000/login 
Content-Type: application/json 

{
    "username": "admin",
    "password": "secret"
}