### home
GET http://localhost:3000/home
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoic2VjcmV0IiwiaXNBZG1pbiI6dHJ1ZSwiYWNjZXNzVG9rZW4iOm51bGwsInJlZnJlc2hUb2tlbiI6bnVsbCwiaWF0IjoxNzExMTQ0Njk5LCJleHAiOjE3MTExNDgyOTl9.NX-0zOTJx-mLwpU1XDQAxkD8XCCnak8zFPsJkqkw3XI


### top-ten crytpocurencies
GET http://localhost:3000/top-ten 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoic2VjcmV0IiwiaXNBZG1pbiI6dHJ1ZSwiYWNjZXNzVG9rZW4iOiJleUpoYkdjaU9pSklVekkxTmlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKcFpDSTZNU3dpZFhObGNtNWhiV1VpT2lKaFpHMXBiaUlzSW5CaGMzTjNiM0prSWpvaWMyVmpjbVYwSWl3aWFYTkJaRzFwYmlJNmRISjFaU3dpWVdOalpYTnpWRzlyWlc0aU9tNTFiR3dzSW5KbFpuSmxjMmhVYjJ0bGJpSTZiblZzYkN3aWFXRjBJam94TnpFeE1UTTNOVGN6TENKbGVIQWlPakUzTVRFeE5ERXhOek45LmJGYlRTa0wxaW1kM0hmVUg3cHdhMnF5X2NLWWg4OWM5cDRveERkdFJPUUUiLCJyZWZyZXNoVG9rZW4iOiJleUpoYkdjaU9pSklVekkxTmlJc0luUjVjQ0k2SWtwWFZDSjkuZXlKcFpDSTZNU3dpZFhObGNtNWhiV1VpT2lKaFpHMXBiaUlzSW5CaGMzTjNiM0prSWpvaWMyVmpjbVYwSWl3aWFYTkJaRzFwYmlJNmRISjFaU3dpWVdOalpYTnpWRzlyWlc0aU9tNTFiR3dzSW5KbFpuSmxjMmhVYjJ0bGJpSTZiblZzYkN3aWFXRjBJam94TnpFeE1UTTNOVGN6TENKbGVIQWlPakUzTVRFeE5EUTNOek45LjdlbXp3elI1eW9SRjhseGhTWGY3bk4wMGl4Tm5qaDI2NUUtOE1tSXcyTDgiLCJpYXQiOjE3MTExMzc2MDUsImV4cCI6MTcxMTE0MTIwNX0.yjUIrQzPR9s6sMI-Mos5px-UvAjnVgfyNG3P7W5HZ8w

### refresh token 
POST http://localhost:3000/api/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoic2VjcmV0IiwiaXNBZG1pbiI6dHJ1ZSwiYWNjZXNzVG9rZW4iOm51bGwsInJlZnJlc2hUb2tlbiI6bnVsbCwiaWF0IjoxNzExMTQ0Njk5LCJleHAiOjE3MTExNDgyOTl9.NX-0zOTJx-mLwpU1XDQAxkD8XCCnak8zFPsJkqkw3XI
Content-Type: application/json 

{
  "id": 1,
  "username": "admin",
  "password": "secret",
  "isAdmin": true,
  "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoic2VjcmV0IiwiaXNBZG1pbiI6dHJ1ZSwiYWNjZXNzVG9rZW4iOm51bGwsInJlZnJlc2hUb2tlbiI6bnVsbCwiaWF0IjoxNzExMTQ0MTgyLCJleHAiOjE3MTExNDc3ODJ9.0ikbAdH8LttGRIJIcgYxyqfsN_uVxnJDL-CCPh-mfYw",
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoic2VjcmV0IiwiaXNBZG1pbiI6dHJ1ZSwiYWNjZXNzVG9rZW4iOm51bGwsInJlZnJlc2hUb2tlbiI6bnVsbCwiaWF0IjoxNzExMTQ0MTgyLCJleHAiOjE3MTExNTEzODJ9.AiYv2JXD5UaoVSstNJabnF0F01qZyAh1_roYJzuCz6g"
}


###
POST http://localhost:3000/api/login 
Content-Type: application/json 

{
    "username": "admin",
    "password": "secret"
}


### test link
POST http://localhost:3000/api/test 

###