### home
GET http://localhost:3000/home
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxMSIsImVtYWlsIjoidXNlcjExQGdtYWlsLmNvbSIsImlhdCI6MTcxMTcxNzgwNiwiZXhwIjoxNzExNzE4NzA2fQ.t4TVT86k-9FA5WFe8O1QDAioZaddQjA7SbQYoSHEejM

### top ten cripto coins 
GET http://localhost:3000/top-ten 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxMSIsImVtYWlsIjoidXNlcjExQGdtYWlsLmNvbSIsImlhdCI6MTcxMTcxNzgwNiwiZXhwIjoxNzExNzE4NzA2fQ.t4TVT86k-9FA5WFe8O1QDAioZaddQjA7SbQYoSHEejM

### refresh token 
POST http://localhost:3000/auth/refresh-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJtb3JhZEBnbWFpbC5jb20iLCJpYXQiOjE3MTE3MTQyOTYsImV4cCI6MTcxMTcxNTE5Nn0.phNCQlqTsus9RYEL9fzOI3DOtPtVGLr3F7l-0FdbXTU
Content-Type: application/json 

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJtb3JhZEBnbWFpbC5jb20iLCJpYXQiOjE3MTE3MTQyOTYsImV4cCI6MTcxMjMxOTA5Nn0.7eyFUIjzWPkIzshEyKxOpVJUB9Ad3F7zQH49pkP7Jsc"
}

###REGISTER

POST http://localhost:3000/auth/register 
Content-Type: application/json 

{
    "username": "user11",
    "password": "secret",
    "email": "user11@gmail.com"
}

### LOGIN
POST http://localhost:3000/auth/login 
Content-Type: application/json 

{
    "username": "user11",
    "password": "secret"
}


